version: "3"

services:
  mysql:
    image: mysql:8.0.30
    ports:
        - 27000:3306
    restart: always
    volumes:
        - ./mysql/datas:/var/lib/mysql
        - ./mysql/conf/my.cnf:/etc/my.cnf:ro
      # TODO: use secrets when deploy
    environment:
        - MYSQL_ROOT_PASSWORD=20172121
#  nacos:
#    image: nacos/nacos-server:v2.0.4
#    # image: zhusaidong/nacos-server-m1:2.0.3
#    container_name: nacos
#    ports:
#      - 27100:8848
#      - 9848:9848
#      - 9849:9849
#    depends_on:
#      - mysql
#    environment:
#      TZ: Asia/Shanghai
#      MODE: standalone
#      SPRING_DATASOURCE_PLATFORM: mysql
#      MYSQL_SERVICE_HOST: mysql
#      MYSQL_SERVICE_PORT: 3306
#      MYSQL_SERVICE_USER: admin
#      MYSQL_SERVICE_PASSWORD: 20172121
#      MYSQL_SERVICE_DB_NAME: pbldb
#      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
#    volumes:
#      - ./nacos/logs/:/home/nacos/logs
